
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets-hook
        args: ['--baseline', '.secrets.baseline']
-   repo: local
    hooks:
      - id: block-binary-docs
        name: Block binary docs (*.rtf, *.docx, *.pdf)
        entry: bash -c 'git diff --cached --name-only | grep -E "\.(rtf|docx?|pdf)$" && echo "Binary docs disallowed; move to docs/binaries/ or archive/." && exit 1 || exit 0'
        language: system
        stages: [commit]
