apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aegis-hil-attest-
spec:
  entrypoint: hil-and-attest
  templates:
    - name: hil-and-attest
      steps:
        - - name: run-hil-tests
            template: hil-tests
        - - name: create-attestation
            template: create-attestation

    - name: hil-tests
      container:
        image: ghcr.io/yourorg/hil-harness:latest
        command: [sh, -c]
        args:
          - |
            # Runs HIL harness; must produce /artifacts/test_summary.json with {"status":"ok"} on success
            /opt/hil/run_tests.sh --out /artifacts || true
        volumeMounts:
          - name: artifacts
            mountPath: /artifacts
      outputs:
        artifacts:
          - name: hil-artifacts
            path: /artifacts

    - name: create-attestation
      inputs:
        artifacts:
          - name: hil-artifacts
            path: /artifacts
      container:
        image: python:3.11-slim
        command: [sh, -c]
        args:
          - |
            pip install kubernetes boto3 && \
            python /opt/aegis/hil_attestor.py --artifacts /artifacts --name "hil-{{workflow.name}}-{{pod.name}}" --upload-s3
        volumeMounts:
          - name: code
            mountPath: /opt/aegis
          - name: artifacts
            mountPath: /artifacts

  volumes:
    - name: code
      hostPath:
        path: ./ops/autonomy
        type: Directory
    - name: artifacts
      emptyDir: {}
