 37
 38
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50
 51
 52
 53
 54
 55
 56
 57
 58
 59
 60
name: Build & Sign Model Artifact (generic)

on:
  workflow_dispatch:
    inputs:
      model_dir:
        description: 'Path to model dir relative to repo (e.g. model_registry/example-tf-model/0.1)'
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  build-sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create deterministic archive
        run: |
          MODEL_DIR="${{ github.event.inputs.model_dir }}"
          python3 scripts/make_deterministic_archive.py "${MODEL_DIR}/saved_model" "/tmp/model.tar.gz"
          sha256sum /tmp/model.tar.gz

      - name: Install cosign
        run: |
          curl -sSLf https://github.com/sigstore/cosign/releases/download/v1.14.1/cosign-linux-amd64 -o /usr/local/bin/cosign
          chmod +x /usr/local/bin/cosign
          cosign version || true

      - name: Decode cosign private key
        if: ${{ secrets.COSIGN_PRIVATE_KEY_B64 != '' }}
        env:
          COSIGN_PRIVATE_KEY_B64: ${{ secrets.COSIGN_PRIVATE_KEY_B64 }}
        run: |
          echo "$COSIGN_PRIVATE_KEY_B64" | base64 --decode > /tmp/cosign_key.pem
          chmod 600 /tmp/cosign_key.pem

      - name: Sign model archive
        if: ${{ secrets.COSIGN_PRIVATE_KEY_B64 != '' }}
        run: |
          cosign sign-blob --key /tmp/cosign_key.pem /tmp/model.tar.gz > /tmp/model.tar.gz.sig
          ls -l /tmp/model.tar.gz.sig

      - name: Upload artifacts (optional)
        if: ${{ secrets.OBJECT_STORE_BUCKET != '' }}
        run: |
          # If provider is AWS and OIDC role is set, assume role via configure-aws-credentials action in separate step
          if [ -n "${{ secrets.OBJECT_STORE_BUCKET }}" ]; then
            aws s3 cp /tmp/model.tar.gz s3://${{ secrets.OBJECT_STORE_BUCKET }}/model-archives/${{ github.run_id }}/model.tar.gz || true
            aws s3 cp /tmp/model.tar.gz.sig s3://${{ secrets.OBJECT_STORE_BUCKET }}/model-archives/${{ github.run_id }}/model.tar.gz.sig || true
          fi

      - name: Upload signature artifact for PR
        uses: actions/upload-artifact@v4
        with:
          name: model-signature
          path: /tmp/model.tar.gz.sig
