  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
 31
 32
 33
 34
 35
 36
 37
 38
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50
 51
 52
 53
 54
 55
 56
 57
 58
 59
 60
 61
 62
 63
 64
 65
 66
 67
 68
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: retrain-on-drift
  namespace: aegis
spec:
  dependencies:
    - name: alert-dep
      eventSourceName: alertmanager-source
      eventName: alertmanager
  triggers:
    - template:
        name: trigger-retrain-workflow
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: retrain-drift-
                namespace: aegis
              spec:
                entrypoint: retrain-and-package
                serviceAccountName: aegis-workflow-sa
                templates:
                  - name: retrain-and-package
                    dag:
                      tasks:
                        - name: start-training
                          template: run-training
                        - name: package-sign
                          template: package-and-sign
                          dependencies: [start-training]
                  - name: run-training
                    container:
                      image: ghcr.io/rsinghunjan/aegis-train:latest
                      command: ["/bin/sh","-c"]
                      args:
                        - |
                          set -euo pipefail
                          # Use helper to parse event JSON (sensor injects event payload into controller annotations/env)
                          /workspace/scripts/retrain_trigger_helper.sh /tmp/event.json /workspace/model_registry/demo-models/cifar_deepspeed/$(date -u +%Y%m%dT%H%M%SZ)
                      volumeMounts:
                        - name: workspace
                          mountPath: /workspace
                  - name: package-and-sign
                    container:
                      image: ghcr.io/rsinghunjan/aegis-tools:latest
                      command: ["/bin/sh","-c"]
                      args:
                        - |
                          set -euo pipefail
                          OUTDIR="/workspace/model_registry/demo-models/cifar_deepspeed/latest"
                          ART="/workspace/artifacts/cifar-$(date -u +%Y%m%dT%H%M%SZ).tar.gz"
                          mkdir -p /workspace/artifacts
                          python3 /workspace/scripts/make_deterministic_archive.py "$OUTDIR" "$ART"
                          /workspace/scripts/package_and_sign_vault.sh "$OUTDIR" "$ART"
                      volumeMounts:
                        - name: workspace
                          mountPath: /workspace
                volumes:
                  - name: workspace
                    emptyDir: {}
  # Optionally add retry/filters to only trigger on specific alert labels/severity
argo/events/sensor-retrain.yaml
