apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aegis-full-train-
  namespace: aegis
spec:
  entrypoint: full-pipeline
  arguments:
    parameters:
      - name: dataset-src
        value: "s3://REPLACE_WITH_BUCKET/datasets/cifar/latest"
      - name: snapshot-prefix
        value: "datasets/cifar"
      - name: feature-prefix
        value: "features/cifar"
      - name: mlflow-tracking-uri
        value: "http://mlflow.aegis.svc.cluster.local:5000"
  templates:
    - name: full-pipeline
      dag:
        tasks:
          - name: ingest
            template: ingest
          - name: features
            template: features
            dependencies: [ingest]
          - name: train
            template: train
            dependencies: [features]
          - name: convert
            template: convert
            dependencies: [train]
          - name: package-sign
            template: package_sign
            dependencies: [convert]

    - name: ingest
      container:
        image: python:3.10-slim
        command: [sh, -c]
        args:
          - pip install boto3 && python3 /workspace/scripts/data_ingest.py --src {{inputs.parameters.dataset-src}} --prefix {{inputs.parameters.snapshot-prefix}} && echo "done"
        volumeMounts:
          - name: workspace
            mountPath: /workspace
      inputs:
        parameters:
          - name: dataset-src
          - name: snapshot-prefix

    - name: features
      container:
        image: ghcr.io/rsinghunjan/aegis-tools:latest
        command: [sh, -c]
        args:
          - pip install pandas pyarrow boto3 && python3 /workspace/features/feature_store.py --input-s3 {{workflow.parameters.dataset-src}} --out-prefix {{workflow.parameters.feature-prefix}} --snapshot-id $(date -u +%Y%m%dT%H%M%SZ)
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: train
      container:
        image: ghcr.io/rsinghunjan/aegis-train:latest
        command: [sh, -c]
        args:
          - export MLFLOW_TRACKING_URI={{workflow.parameters.mlflow-tracking-uri}} && python3 /workspace/training/train_deepspeed.py --out-dir /workspace/model_registry/demo-models/cifar_deepspeed/$(date -u +%Y%m%dT%H%M%SZ) --max-epochs 1
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: convert
      container:
        image: ghcr.io/rsinghunjan/aegis-tools:latest
        command: [sh, -c]
        args:
          - python3 /workspace/conversion/convert_to_onnx.py /workspace/model_registry/demo-models/cifar_deepspeed/latest/pytorch_model.bin /workspace/model_registry/demo-models/cifar_deepspeed/latest/model.onnx
        volumeMounts:
          - name: workspace
            mountPath: /workspace

    - name: package_sign
      container:
        image: ghcr.io/rsinghunjan/aegis-tools:latest
        command: [sh, -c]
        args:
          - /workspace/scripts/package_and_attest.sh /workspace/model_registry/demo-models/cifar_deepspeed/latest /workspace/artifacts/cifar-$(date -u +%Y%m%dT%H%M%SZ).tar.gz
        volumeMounts:
          - name: workspace
            mountPath: /workspace

  volumes:
    - name: workspace
      emptyDir: {}
