apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: python:3.10-slim
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "" # set via k8s secret or env in production
        - name: MLFLOW_S3_BUCKET
          value: "" # set to your bucket
        - name: AWS_REGION
          value: "" # optional
        - name: SQLALCHEMY_DATABASE_URI
          value: "sqlite:///mlflow.db" # replace with managed DB in prod
        - name: ARTIFACT_ROOT
          value: "s3://${MLFLOW_S3_BUCKET}/mlflow-artifacts"
        - name: MLFLOW_TRACKING_URI
          value: "http://127.0.0.1:5000"
        ports:
        - containerPort: 5000
        command: ["sh", "-c"]
        args:
          - |
            pip install mlflow[extras] boto3 waitress && \
            mlflow server \
              --backend-store-uri ${SQLALCHEMY_DATABASE_URI} \
              --default-artifact-root ${ARTIFACT_ROOT} \
              --host 0.0.0.0 --port 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
