apiVersion: {{ .apiVersion | default "aadpodidentity.k8s.io/v1" }}
kind: {{ .kind | default "AzureIdentity" }}
metadata:
  name: {{ .name }}
spec:
  # type: 1 => UserAssigned MSIs
  type: {{ .type | default 1 }}
  resourceID: "{{ .resourceID }}"     # /subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<uami>
  clientID: "{{ .clientID }}"
---
apiVersion: {{ .bindingApiVersion | default "aadpodidentity.k8s.io/v1" }}
kind: {{ .bindingKind | default "AzureIdentityBinding" }}
metadata:
  name: {{ .bindingName }}
spec:
  azureIdentity: {{ .name }}
  selector: {{ .selector }}
---
# v2-style examples (may need adaptation to your operator)
apiVersion: {{ .v2ApiVersion | default "aadpodidentity.io/v1" }}
kind: {{ .v2AssignedKind | default "AzureAssignedIdentity" }}
metadata:
  name: {{ .name }}-assigned
spec:
  clientID: "{{ .clientID }}"
  resourceID: "{{ .resourceID }}"
  azureIdentityBinding: {{ .bindingName }}
---
apiVersion: {{ .v2ApiVersion | default "aadpodidentity.io/v1" }}
kind: {{ .v2BindingKind | default "AzureIdentityBinding" }}
metadata:
  name: {{ .bindingName }}
spec:
  azureIdentity: {{ .name }}
  selector: {{ .selector }}
